version: '3.7'

services: 
  currency-exchange:
    image: florajiaqi/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports: 
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka

  currency-conversion:
    image: florajiaqi/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    ports: 
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka

  api-gateway:
    image: florajiaqi/mmv2-api-gateway:0.0.1-SNAPSHOT
    ports: 
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka


  naming-service:
    image: florajiaqi/mmv2-naming-service:0.0.1-SNAPSHOT
    ports: 
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: 
